// MENU ACTION TYPE
export const COLLAPSE_MENU = "COLLAPSE_MENU";
export const COLLAPSE_TOGGLE = "COLLAPSE_TOGGLE";
export const FULL_SCREEN = "FULL_SCREEN";
export const FULL_SCREEN_EXIT = "FULL_SCREEN_EXIT";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const NAV_CONTENT_LEAVE = "NAV_CONTENT_LEAVE";
export const NAV_COLLAPSE_LEAVE = "NAV_COLLAPSE_LEAVE";

// AUTH ACTION TYPE
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESET = "AUTH_RESET";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAN_AUTH = "CLEAN_AUTH";

// PRODUCT ACTION TYPE
export const ALL_PRODUCT = "ALL_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const LIST_ARTIST = "LIST_ARTIST";
export const LIST_STICKER_TYPE = "LIST_STICKER_TYPE";
export const LIST_PRINT_MODE = "LIST_PRINT_MODE";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_IMAGES = "CREATE_PRODUCT_IMAGES";
export const LIST_ALL_PRODUCT_INFO = "LIST_ALL_PRODUCT_INFO";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const LIST_PRODUCT_IMAGESET = "LIST_PRODUCT_IMAGESET";
export const UPDATE_PRODUCT_IMAGESET = "UPDATE_PRODUCT_IMAGESET";
export const UPLOAD_PRODUCT = "UPLOAD_PRODUCT";
export const REUPLOAD_PRODUCT = "REUPLOAD_PRODUCT";
export const GENERATE_PRODUCT = "GENERATE_PRODUCT";
export const UPLOAD_STICKERS_PDF = "UPLOAD_STICKERS_PDF";
export const CLEAN_PRODUCT = "CLEAN_PRODUCT";

///--price--///
export const LIST_PRICE_TSHIRTS = "LIST_PRICE_TSHIRTS";
export const LIST_PRICE_STICKERS = "LIST_PRICE_STICKERS";
export const LIST_PRICE_MUGS = "LIST_PRICE_MUGS";
export const LIST_PRICE_TOTEBAGS = "LIST_PRICE_TOTEBAGS";
export const LIST_PRICE_CUSHION_COVERS = "LIST_PRICE_CUSHION_COVERS";
export const LIST_PRICE_HOODIES = "LIST_PRICE_HOODIES";
export const LIST_PRICE_KIDS = "LIST_PRICE_KIDS";

// KEYWORD ACTION TYPE
export const ALL_KEYWORD = "ALL_KEYWORD";
export const CREATE_KEYWORD = "CREATE_KEYWORD";
export const CLEAN_KEYWORD = "CLEAN_KEYWORD";
export const UPDATE_KEYWORD = "UPDATE_KEYWORD";
export const DELETE_KEYWORD = "DELETE_KEYWORD";
export const KEYWORD_ERROR = "KEYWORD_ERROR";

//CATEGORY ACTION TYPE
export const ALL_CATEGORY = "ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const MERGE_CATEGORY = "MERGE_CATEGORY";
export const CLEAN_CATEGORY = "CLEAN_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

//TRADEMARK ACTION TYPE
export const CLEAN_TRADEMARK = "CLEAN_TRADEMARK";
export const TRADEMARK_CREATE_WORD = "TRADEMARK_CREATE_WORD";
export const TRADEMARK_UPDATE_WORD = "TRADEMARK_UPDATE_WORD";
export const TRADEMARK_DELETE_WORD = "TRADEMARK_DELETE_WORD";
export const TRADEMARK_UPDATE_CLASS_WORD = "TRADEMARK_UPDATE_CLASS_WORD";
export const TRADEMARK_UPDATE_CLASS_WORDS_LIST = "TRADEMARK_UPDATE_CLASS_WORDS_LIST";
export const TRADEMARK_ERROR = "TRADEMARK_ERROR";

//VARIANT ACTION TYPE
export const LIST_COLOR = "LIST_COLOR";
export const LIST_SIZE = "LIST_SIZE";
export const LIST_TYPE = "LIST_TYPE";
export const CLEAN_VARIANT = "CLEAN_VARIANT";
export const ALL_IMAGE_VARIANT = "ALL_IMAGE_VARIANT";
export const UPDATE_IMAGE_VARIANT = "UPDATE_IMAGE_VARIANT";
export const ALL_MERCHANT_PRICE_VARIANT = "ALL_MERCHANT_PRICE_VARIANT";
export const UPDATE_MERCHANT_PRICE_VARIANT = "UPDATE_MERCHANT_PRICE_VARIANT";
export const ALL_DESCRIPTION_VARIANT = "ALL_DESCRIPTION_VARIANT";
export const UPDATE_DESCRIPTION_VARIANT = "UPDATE_DESCRIPTION_VARIANT";
export const ALL_PRICE_VARIANT = "ALL_PRICE_VARIANT";
export const ADD_PRICE_VARIANT = "ADD_PRICE_VARIANT";
export const DELETE_PRICE_VARIANT = "DELETE_PRICE_VARIANT";
export const DEFAULT_PRICE_VARIANT = "DEFAULT_PRICE_VARIANT";
export const CREATE_VARIANT = "CREATE_VARIANT";
export const UPDATE_VARIANT = "UPDATE_VARIANT";
export const DELETE_VARIANT = "DELETE_VARIANT";
export const VARIANT_ERROR = "VARIANT_ERROR";
export const CLEAN_SIZE = "CLEAN_SIZE";
export const CLEAN_COLOR = "CLEAN_COLOR";
export const CLEAN_TYPE = "CLEAN_TYPE";

//SETTING ACTION TYPE
export const CLEAN_SETTING = "CLEAN_SETTING";
export const UPDATE_SETTING = "UPDATE_SETTING";
export const GET_SETTING = "GET_SETTING";
export const UPDATE_ETSY_SETTING = "UPDATE_ETSY_SETTING";
export const SETTING_ERROR = "SETTING_ERROR";

//ARTIST ACTION TYPE
export const ALL_ARTIST = "ALL_ARTIST";
export const CREATE_ARTIST = "CREATE_ARTIST";
export const CLEAN_ARTIST = "CLEAN_ARTIST";
export const UPDATE_ARTIST = "UPDATE_ARTIST";
export const DELETE_ARTIST = "DELETE_ARTIST";
export const ARTIST_ERROR = "ARTIST_ERROR";

export const ALL_USER = "ALL_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_ERROR = "USER_ERROR";
